// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBoyrXnchgOWbL4lkgRZRkO5GOwBwLdUsw',
    appId: '1:984945488613:web:baf7240e30e43d52afda0c',
    messagingSenderId: '984945488613',
    projectId: 'educational-app-8b1e7',
    authDomain: 'educational-app-8b1e7.firebaseapp.com',
    storageBucket: 'educational-app-8b1e7.appspot.com',
    measurementId: 'G-DDT38NP0F1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCane2xSvaNci8PS6dY2b7uN_jRWbGLIus',
    appId: '1:984945488613:android:85b3e4b782242058afda0c',
    messagingSenderId: '984945488613',
    projectId: 'educational-app-8b1e7',
    storageBucket: 'educational-app-8b1e7.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCr1mQxnqRXRVoxas1RJ_tovG51Is02-J8',
    appId: '1:984945488613:ios:5ae0056b04bd64cbafda0c',
    messagingSenderId: '984945488613',
    projectId: 'educational-app-8b1e7',
    storageBucket: 'educational-app-8b1e7.appspot.com',
    iosBundleId: 'com.example.educationalApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCr1mQxnqRXRVoxas1RJ_tovG51Is02-J8',
    appId: '1:984945488613:ios:5ae0056b04bd64cbafda0c',
    messagingSenderId: '984945488613',
    projectId: 'educational-app-8b1e7',
    storageBucket: 'educational-app-8b1e7.appspot.com',
    iosBundleId: 'com.example.educationalApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBoyrXnchgOWbL4lkgRZRkO5GOwBwLdUsw',
    appId: '1:984945488613:web:620ade89779f22c9afda0c',
    messagingSenderId: '984945488613',
    projectId: 'educational-app-8b1e7',
    authDomain: 'educational-app-8b1e7.firebaseapp.com',
    storageBucket: 'educational-app-8b1e7.appspot.com',
    measurementId: 'G-SSZM94EZPF',
  );
}
